version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_ssh_host'] = '${GITLAB_SSH_HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SHELL_SSH_HOST}
        gitlab_rails['time_zone'] = '${GITLAB_TZ}'
    ports:
      - '8000:80'
      - '4443:443'
      - '22:22'
    volumes:
      - /srv/gitlab/config:/etc/gitlab:Z
      - /srv/gitlab/logs:/var/log/gitlab:Z
      - /srv/gitlab/data:/var/opt/gitlab:Z
